.TH "NeuroneB" 3 "Wed Mar 21 2018" "Reseaux Neuronal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NeuroneB \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNeurone\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNeuroneB\fP (int taille)"
.br
.ti -1c
.RI "\fBNeuroneB\fP (int taille, std::vector< double > *x, double biais_w)"
.br
.ti -1c
.RI "void \fBprintWeight\fP ()"
.br
.ti -1c
.RI "void \fBaleaWeights\fP ()"
.br
.ti -1c
.RI "void \fBlearn\fP (std::vector< double > x, double o, double k, double mu)"
.br
.ti -1c
.RI "double \fBfw_sum\fP (std::vector< double > x) const "
.br
.ti -1c
.RI "int \fBgetNbPoids\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NeuroneB::NeuroneB (int taille)"
Constructeur du \fBNeurone\fP avec biais  \fBNeuroneB::NeuroneB\fP 
.PP
\fBParameters:\fP
.RS 4
\fItaille\fP Taille du neurone 
.RE
.PP

.SS "NeuroneB::NeuroneB (int taille, std::vector< double > * x, double biais_w)"
Constructeur du \fBNeurone\fP avec biais  \fBNeuroneB::NeuroneB\fP 
.PP
\fBParameters:\fP
.RS 4
\fItaille\fP Taille du neurone 
.br
\fIx\fP Vecteur de poids 
.br
\fIbiais_w\fP Valeur du biais 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void NeuroneB::aleaWeights ()\fC [virtual]\fP"
Génération aléatoire des poids  \fBNeuroneB::aleaWeights\fP 
.PP
Reimplemented from \fBNeurone\fP\&.
.SS "double NeuroneB::fw_sum (std::vector< double > x) const\fC [virtual]\fP"
Méthode de somme du vecteur de poids  \fBNeuroneB::fw_sum\fP 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Vecteur de poids 
.RE
.PP
\fBReturns:\fP
.RS 4
Somme des poids 
.RE
.PP

.PP
Reimplemented from \fBNeurone\fP\&.
.SS "int NeuroneB::getNbPoids ()\fC [virtual]\fP"
\fBNeuroneB::getNbPoids\fP 
.PP
\fBReturns:\fP
.RS 4
Nombre de poids 
.RE
.PP

.PP
Reimplemented from \fBNeurone\fP\&.
.SS "void NeuroneB::learn (std::vector< double > x, double o, double k, double mu)\fC [virtual]\fP"
Méthode d'apprentissage (cf \fBNeurone::fw_sum\fP, cf \fBNeurone::fw_activate\fP, cf \fBNeurone::derive_activate\fP)  \fBNeurone::learn\fP 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP Vecteur de poids 
.br
\fIo\fP Valeur attendue 
.br
\fIk\fP Valeur du biais 
.br
\fImu\fP Taux d'apprentissage | Learning rate 
.RE
.PP

.PP
Reimplemented from \fBNeurone\fP\&.
.SS "void NeuroneB::printWeight ()\fC [virtual]\fP"
Affichage des poids  \fBNeuroneB::printWeight\fP 
.PP
Reimplemented from \fBNeurone\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Reseaux Neuronal from the source code\&.
