.TH "OptionTab" 3 "Wed Mar 21 2018" "Reseaux Neuronal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionTab \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddOption\fP (const \fBOption\fP &opt)"
.br
.ti -1c
.RI "void \fBPrintOptions\fP () const "
.br
.ti -1c
.RI "int \fBGetOptionID\fP (const std::string &opt) const "
.br
.ti -1c
.RI "std::string \fBGetArgument\fP (const std::string &opt) const "
.br
.ti -1c
.RI "std::string \fBGetRaccour\fP (const std::string &opt) const "
.br
.ti -1c
.RI "std::string \fBGetTypeOption\fP (const std::string &opt) const "
.br
.ti -1c
.RI "std::string \fBGetIntitul\fP (const std::string &opt) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Reseaux Neuronal from the source code\&.
