.TH "Option" 3 "Wed Mar 21 2018" "Reseaux Neuronal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Option \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOption\fP ()"
.br
.ti -1c
.RI "\fBOption\fP (int id, const std::string &intitul, const std::string &m_rac, const std::string &type, const std::string &m_description)"
.br
.ti -1c
.RI "int \fBGetOptionId\fP () const "
.br
.ti -1c
.RI "std::string \fBGetOptionType\fP () const "
.br
.ti -1c
.RI "std::string \fBGetOptionInt\fP () const "
.br
.ti -1c
.RI "std::string \fBGetOptionRac\fP () const "
.br
.ti -1c
.RI "void \fBSetOptionType\fP (std::string &t)"
.br
.ti -1c
.RI "void \fBSetOptionInt\fP (std::string &intitul)"
.br
.ti -1c
.RI "void \fBSetOptionRac\fP (std::string &rac)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Option::Option ()"
Constructeur d'option vide  \fBOption::Option\fP 
.SH "Member Function Documentation"
.PP 
.SS "int Option::GetOptionId () const"
\fBOption::GetOptionId\fP 
.PP
\fBReturns:\fP
.RS 4
ID de l'option 
.RE
.PP

.SS "string Option::GetOptionInt () const"
\fBOption::GetOptionInt\fP 
.PP
\fBReturns:\fP
.RS 4
Intitulé de l'option 
.RE
.PP

.SS "string Option::GetOptionRac () const"
\fBOption::GetOptionRac\fP 
.PP
\fBReturns:\fP
.RS 4
Raccourci de l'option 
.RE
.PP

.SS "string Option::GetOptionType () const"
\fBOption::GetOptionType\fP 
.PP
\fBReturns:\fP
.RS 4
\fBType\fP d'option 
.RE
.PP

.SS "void Option::SetOptionInt (std::string & intitul)"
\fBOption::SetOptionInt\fP 
.PP
\fBParameters:\fP
.RS 4
\fIintitul\fP Nouveau Intitulé 
.RE
.PP

.SS "void Option::SetOptionRac (std::string & rac)"
\fBOption::SetOptionRac\fP 
.PP
\fBParameters:\fP
.RS 4
\fIrac\fP Nouveau Raccourci 
.RE
.PP

.SS "void Option::SetOptionType (std::string & t)"
\fBOption::SetOptionType\fP 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP Nouveau type d'option 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Reseaux Neuronal from the source code\&.
