.TH "Reseau" 3 "Wed Mar 21 2018" "Reseaux Neuronal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reseau \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReseau\fP (int, std::vector< int >)"
.br
.ti -1c
.RI "std::vector< double > \fBfire_all\fP (std::vector< double > input, double k)"
.br
.ti -1c
.RI "void \fBlearn\fP (std::vector< std::vector< std::vector< double > > > jeuxTest)"
.br
.ti -1c
.RI "void \fBbackPropagation\fP (std::vector< double > output, double k, double eta)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Reseaux Neuronal from the source code\&.
